### ISSUE TITLE
The existing environment seems to be missing some dependencies, can you update it in time.

### ISSUE THREAD

**Issue by 464hee** [drivendataorg/visiomel-melanoma-runtime#19]
warn(f"Failed to load image Python extension: {e}")
/opt/conda/envs/condaenv/lib/python3.10/site-packages/torchvision/io/image.py:13: UserWarning: Failed to load image Python extension: libjpeg.so.8: cannot open shared object file: No such file or directory

**Comment by ejm714** [comment]
@464hee can you provide the actual code that errored? I'm assuming this was on some import

**Comment by ejm714** [comment]
I was able to reproduce this warning with `from torchvision import datasets` and have implemented a fix in #20
