### ISSUE TITLE
Please provide a environment to run the scoring script file

### ISSUE THREAD

**Issue by johntiger1** [drivendataorg/visiomel-melanoma-runtime#26]
https://github.com/drivendataorg/visiomel-melanoma-runtime/blob/df507909360246bc5a8e0852dd2a08724e8c1a38/README.md?plain=1#L154

```(.env) johnchen@Johns-MacBook-Pro visiomel-melanoma-runtime % python3 scripts/score.py
Traceback (most recent call last):
  File "/Users/johnchen/self/visiomel-melanoma-runtime/scripts/score.py", line 4, in <module>
    from loguru import logger
ModuleNotFoundError: No module named 'loguru'```

**Comment by ejm714** [comment]
The environment is specified in the `environment-*.yml` files in the [runtime](https://github.com/drivendataorg/visiomel-melanoma-runtime/tree/main/runtime) folder.

For example, to create a conda environment for a CPU machine, you'd run
```
conda env create -f runtime/environment-cpu.yml
source activate condaenv
```

**Comment by ejm714** [comment]
There are also only three requirements for the scoring script (as you can see from the imports at the top of the script) so you could instead create a new environment and then simply pip install pandas, loguru, and scikit-learn.
