### ISSUE TITLE
ValueError: incorrect coordinate type ERROR conda.cli.main_run:execute(47): `conda run python main.py` failed.

### ISSUE THREAD

**Issue by johntiger1** [drivendataorg/visiomel-melanoma-runtime#27]
https://github.com/drivendataorg/visiomel-melanoma-runtime/blob/df507909360246bc5a8e0852dd2a08724e8c1a38/examples_src/benchmark/main.py#L12

To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.
<jemalloc>: MADV_DONTNEED does not work (memset will be used instead)
<jemalloc>: (This is the expected behaviour if you are running under QEMU)
Traceback (most recent call last):
  File "/code_execution/main.py", line 6, in <module>
    DATA_ROOT = Path("/code_execution/data/")
ValueError: incorrect coordinate type
ERROR conda.cli.main_run:execute(47): `conda run python main.py` failed. (See above for error)

**Comment by ejm714** [comment]
Hi @johntiger1, can you provide more details on the steps to take to reproduce this error? What commands did you run? Let us know if you followed the instructions in the readme to pull the latest image, pack the example submission, and then run the test submission.

**Comment by johntiger1** [comment]
I resolved this by simply changing the `Path` to `str` instead
